<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Chapter-2---Elements-of-Matrix-Theory" data-toc-modified-id="Chapter-2---Elements-of-Matrix-Theory-1">Chapter 2 - Elements of Matrix Theory</a></span><ul class="toc-item"><li><span><a href="#2.1.2-The-Jordan-Normal-Form" data-toc-modified-id="2.1.2-The-Jordan-Normal-Form-1.1">2.1.2 The Jordan Normal Form</a></span><ul class="toc-item"><li><span><a href="#Example-2.5-Revisiting-the-wireless-sensor-network-example" data-toc-modified-id="Example-2.5-Revisiting-the-wireless-sensor-network-example-1.1.1">Example 2.5 Revisiting the wireless sensor network example</a></span></li><li><span><a href="#NumPy/-SciPy-approach" data-toc-modified-id="NumPy/-SciPy-approach-1.1.2">NumPy/ SciPy approach</a></span></li><li><span><a href="#SymPy-approach" data-toc-modified-id="SymPy-approach-1.1.3">SymPy approach</a></span></li></ul></li><li><span><a href="#2.1.3-Semi-convergence-and-convergence-for-discrete-time-linear-systems" data-toc-modified-id="2.1.3-Semi-convergence-and-convergence-for-discrete-time-linear-systems-1.2">2.1.3 Semi-convergence and convergence for discrete-time linear systems</a></span><ul class="toc-item"><li><span><a href="#Definition-2.6-(Spectrum-and-spectral-radius-of-a-matrix)" data-toc-modified-id="Definition-2.6-(Spectrum-and-spectral-radius-of-a-matrix)-1.2.1">Definition 2.6 (Spectrum and spectral radius of a matrix)</a></span></li></ul></li><li><span><a href="#2.2.1-The-spectral-radius-for-row-stochastic-matrices" data-toc-modified-id="2.2.1-The-spectral-radius-for-row-stochastic-matrices-1.3">2.2.1 The spectral radius for row-stochastic matrices</a></span><ul class="toc-item"><li><span><a href="#Theorem-2.8-(Geršgorin-Disks-Theorem)" data-toc-modified-id="Theorem-2.8-(Geršgorin-Disks-Theorem)-1.3.1">Theorem 2.8 (Geršgorin Disks Theorem)</a></span></li></ul></li><li><span><a href="#2.3.3-Applications-to-matrix-powers-and-averaging-systems" data-toc-modified-id="2.3.3-Applications-to-matrix-powers-and-averaging-systems-1.4">2.3.3 Applications to matrix powers and averaging systems</a></span><ul class="toc-item"><li><span><a href="#Theorem-2.13-(Powers-of-non-negative-matrices-with-a-simple-and-strictly-dominant-eigenvalue)" data-toc-modified-id="Theorem-2.13-(Powers-of-non-negative-matrices-with-a-simple-and-strictly-dominant-eigenvalue)-1.4.1">Theorem 2.13 (Powers of non-negative matrices with a simple and strictly dominant eigenvalue)</a></span><ul class="toc-item"><li><span><a href="#Example-2.14-Wireless-sensor-network" data-toc-modified-id="Example-2.14-Wireless-sensor-network-1.4.1.1">Example 2.14 Wireless sensor network</a></span></li></ul></li></ul></li><li><span><a href="#Exercises-2.18" data-toc-modified-id="Exercises-2.18-1.5">Exercises 2.18</a></span></li></ul></li></ul></div>

In [1]:
%matplotlib widget

# Import packages
import scipy.linalg as spla
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import networkx as nx
from sympy import Matrix
import sys, os
# For interactive graphs
import ipywidgets as widgets

# Import self defined functions
#import ch1_lib  # Chapter 1 specific library
sys.path.insert(1, os.path.join(sys.path[0], '..'))  # Need to call this for importing library from parent folder
import lib  # General library

# Settings
custom_figsize= (6, 4) # Might need to change this value to fit the figures to your screen
custom_figsize_square = (5, 5)  

In [2]:
def matprint(mat, fmt="g"):
    """
    Own defined function to beautiful print matrices in the output.
    """
    # Handling 1d-arrays
    if np.ndim(mat) == 1:
        mat = mat.reshape(mat.shape[0], 1)
    # Handling column spaces
    col_maxes = [max([len(("{:"+fmt+"}").format(x)) for x in col]) for col in mat.T]

    for x in mat:
        for i, y in enumerate(x):
            if i == 0:
                print(("|  {:"+str(col_maxes[i])+fmt+"}").format(y), end="  ")
            else:                    
                print(("{:"+str(col_maxes[i])+fmt+"}").format(y), end="  ")
        print("|")


def plot_spectrum(M, ax):
    """
    Scatter plot of eigs in complex plane overlayed by radius circle
    """
    eigvals = spla.eig(M)[0]  # Extract only eigenvalues
    
    ax.scatter(eigvals.real, eigvals.imag)
    ax.set_xlim(-1.05,1.05)
    ax.set_ylim(-1.05,1.05)
    
    r = max(abs(eigvals))  # Note: abs() automatically calculated the magnitude of complex values
    circle=mpl.patches.Circle((0,0),radius=r,alpha=.2,ec='black')
    ax.add_patch(circle)
    ax.axhline(0, color='black', ls='--', linewidth=1)
    ax.axvline(0, color='black', ls='--', linewidth=1)
    return eigvals, ax


def plot_gersgorin_disks(M, ax):
    """
    Scatter plot of eigenvalues overlayed with gersgorin disks (marked with green edges)
    """
    eigvals, ax = plot_spectrum(M, ax)
    
    row_sums = M.sum(axis=1)
    for i in range(M.shape[0]):
        ax.add_patch(mpl.patches.Circle((M[i,i],0),radius=row_sums[i]-M[i,i],
                                    alpha=.6/M.shape[0], ec='green'))

**TODO:**

Chapter 2:
- randomly generate a matrix, compute Jordan form, plot spectrum  -- DONE
- randomly generate a matrix and plot the Gersgorin disks -- DONE
- compute powers of a primitive row-stochastic matrix and show it converges to rank 1 -- DONE
- illustrate dynamics of algorithms 2.18 and 2.19

# Chapter 2 - Elements of Matrix Theory
These Jupyter Notebook scripts contain some examples, visualization and supplements accompanying the book "Lectures on Network Systems" by Francesco Bullo http://motion.me.ucsb.edu/book-lns/. These scripts are published with the MIT license. **Make sure to run the first cell above to import all necessary packages and functions and adapt settings in case.** In this script it is necessary to execute cell by cell chronologically due to reocurring examples. (Tip: Use the shortcut Shift+Enter to execute each cell). Most of the functions are kept in separate files to keep this script neat.

## 2.1.2 The Jordan Normal Form
### Example 2.5 Revisiting the wireless sensor network example
The following cells are showing the computation of the Jordan Normal Form $J$, the invertible transformation matrix $T$ and some of its dependencies. 

In [3]:
# Defining the A matrix again
A = np.array([[1/2, 1/2, 0., 0.],
              [1/4, 1/4, 1/4, 1/4],
              [0., 1/3, 1/3, 1/3],
              [0., 1/3, 1/3, 1/3]
])

There is the possibility to calculate the Jordan Normal Form directly with the package SymPy https://docs.sympy.org/latest/index.html. However, we are determining the Jordan Normal Form via determining the generalized eigenvectors (read more for literature recommendations about generalized eigenvectors in the book) with the SciPy package first to discuss some possibilities and problems with non symbolic toolboxes.

### NumPy/ SciPy approach

From the documentation of scipy.linalg.eig: *'Solve an ordinary or generalized eigenvalue problem of a square matrix.'*

In [4]:
# Right eigenvectors
lambdas, eigv = spla.eig(A)

# Left eigenvectors
lambdas2, eigw = spla.eig(A.T)

Due to numerical instabilities, the zero values are not reflected and it can be seen, how the expected eigenvalue of 1 is not precise. The zeros can be fixed with:

In [5]:
def correct_close_to_zero(M, tol=1e-12):
    M.real[abs(M.real) < tol] = 0.0
    if M.imag.any():
        M.imag[abs(M.imag) < tol] = 0.0
    return M

eigv_cor = correct_close_to_zero(eigv)
eigw_cor = correct_close_to_zero(eigw)
lambdas_cor = correct_close_to_zero(lambdas)
lambdas2_cor = correct_close_to_zero(lambdas2)

print("Right eigenvectors:")
matprint(eigv_cor)
print("\n")
print("Left eigenvectors:")
matprint(eigw_cor)
print("\n")
print("Eigenvalues (right):")
matprint(lambdas_cor)
print("\n")
print("Eigenvalues (left) for matching later:")
matprint(lambdas2_cor)

Right eigenvectors:
|  -0.5  0.855025   0.555542          0  |
|  -0.5  0.110013  -0.719612          0  |
|  -0.5  -0.35835   0.294561  -0.707107  |
|  -0.5  -0.35835   0.294561   0.707107  |


Left eigenvectors:
|  0.324443  -0.733894  -0.333766          0  |
|  0.648886  -0.188856   0.864677          0  |
|  0.486664   0.461375  -0.265456  -0.707107  |
|  0.486664   0.461375  -0.265456   0.707107  |


Eigenvalues (right):
|          1+0j  |
|   0.564333+0j  |
|  -0.147667+0j  |
|          0+0j  |


Eigenvalues (left) for matching later:
|          1+0j  |
|   0.564333+0j  |
|  -0.147667+0j  |
|          0+0j  |


There are two options now for $T^{-1}$: Taking the inverse of the right eigenvectors (which contains again numerical instabilities) or building it from the left eigenvectors, what would include some sorting to match the eigenvalue order from the  right eigenvector (often it is the case, that they are already aligned since calling scipy.linalg.eig twice on a matrix with the same eigenvalues).

In [6]:
T = eigv_cor.copy()*-1  # Rescale the eigenvectors to match eigenvalues later
# Sorting if necessary, remember to use transpose, since in T^-1 the rows represent the left eigenvectors.
Tinv = eigw_cor.T.copy()

Now we can simply compute J, when compared, is fairly close to the solution in the book, however, due to numerical intabilities not precise. Further on, the order of the eigenvalues might be different than the on from the book.

In [7]:
J = correct_close_to_zero(Tinv@A@T)
print("Jordan Normal Form via SciPy/Numpy:")
matprint(J)

Jordan Normal Form via SciPy/Numpy:
|  0.973329        0          0  0  |
|         0  0.55245          0  0  |
|         0        0  -0.142357  0  |
|         0        0          0  0  |


### SymPy approach

Now we use a symbolic toolbox package SymPy from python as a blackbox. Note, that also here the order of the eigenvalues might be different!

In [8]:
Asym = Matrix(A) # Sympy Matrix toolbox object
Tsym, Jsym = Asym.jordan_form()

Here we can compare them with our previous results:

In [9]:
print("Jordan Normal Form SymPy:")
matprint(np.array(Jsym).astype(np.float64))
print("Jordan Normal Form SciPy:")
matprint(J)

Jordan Normal Form SymPy:
|  0  0          0         0  |
|  0  1          0         0  |
|  0  0  -0.147667         0  |
|  0  0          0  0.564333  |
Jordan Normal Form SciPy:
|  0.973329        0          0  0  |
|         0  0.55245          0  0  |
|         0        0  -0.142357  0  |
|         0        0          0  0  |


## 2.1.3 Semi-convergence and convergence for discrete-time linear systems


### Definition 2.6 (Spectrum and spectral radius of a matrix)
We display the spectrum of the previous A matrix with the spectrum radius for visualization purpose. Additionally, we also show how the spectrum of a randomly generated matrix.

In [10]:
fig, ax213 = plt.subplots(figsize=custom_figsize_square)
plot_spectrum(A, ax213);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [11]:
n_M1=8

# A unifornmly distributed, positive, row stochastic matrix vs not row stochastic
M1 = np.random.uniform(0, 1,(n_M1,n_M1))
M1 = M1 / M1.sum(axis=1, keepdims=1) # Row-stochastic
M2 = M1 - 0.05 # Not row-stochastic

fig, (ax2131, ax2132) = plt.subplots(1,2, figsize=(custom_figsize_square[0]*2, custom_figsize_square[1]))
plot_spectrum(M1, ax2131);
plot_spectrum(M2, ax2132);

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## 2.2.1 The spectral radius for row-stochastic matrices
### Theorem 2.8 (Geršgorin Disks Theorem)

Similar to before, the Geršgorin Disks are now visualized for a row-stochastic matrix and another matrix.

In [12]:
fig, (ax2211, ax2212) = plt.subplots(1,2, figsize=(custom_figsize_square[0]*2, custom_figsize_square[1]))
plot_gersgorin_disks(M1, ax2211)
plot_gersgorin_disks(M2, ax2212)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

## 2.3.3 Applications to matrix powers and averaging systems

### Theorem 2.13 (Powers of non-negative matrices with a simple and strictly dominant eigenvalue)

Here is an example for Theorem 2.13, which shows, how the powers of primitive, row-stochastic matrices converges to rank 1. This is also done for the wireless sensor network example.

#### Example 2.14 Wireless sensor network
In the book it is shown, that the wireless sensor network matrix is primitive. Here, the eigenvectors and eigenvalues are printed again and compared for the semi convergence result $\lim_{k \to \infty} A^k = \mathbb{1}_n w^T$ to demonstrate Theorem 2.13 for a row-stochastic matrix. 

In [13]:
print("Left eigenvectors of A:")
matprint(eigw_cor)
print("\n")

print("Eigenvalues (left) of A:")
matprint(lambdas2_cor)
print("\n")

print("Normalizing dominant eigenvector:")
dom_eigv = eigw_cor[:, 0] / sum(eigw_cor[:, 0])
matprint(dom_eigv)
print("\n")

print("Convergence result of A:")
matprint(np.linalg.matrix_power(A, 50))
print("\n")

print("equals 1n*w^T")
matprint(np.ones((4,1))@dom_eigv[:, None].T)

Left eigenvectors of A:
|  0.324443  -0.733894  -0.333766          0  |
|  0.648886  -0.188856   0.864677          0  |
|  0.486664   0.461375  -0.265456  -0.707107  |
|  0.486664   0.461375  -0.265456   0.707107  |


Eigenvalues (left) of A:
|          1+0j  |
|   0.564333+0j  |
|  -0.147667+0j  |
|          0+0j  |


Normalizing dominant eigenvector:
|  0.166667  |
|  0.333333  |
|      0.25  |
|      0.25  |


Convergence result of A:
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |


equals 1n*w^T
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |
|  0.166667  0.333333  0.25  0.25  |


Below is a randomly generated example to show, that primitive, row-stochastic matrices always converge to rank 1. *Note: The code is not robust for semisimple eigenvalue of 1*

In [14]:
# Creating a new random primitive (positiv), row stochastic matrix here
n_M11=5
M11 = np.random.uniform(0, 1,(n_M11,n_M11))
M11 = M11 / M11.sum(axis=1, keepdims=1) # Row-stochastic
print("Random primitive row-stochastic matrix M:")
matprint(M11)
print("\n")

print("Left eigenvectors of M:")
l_M, m_eigv = spla.eig(M11.T)
m_eigv = correct_close_to_zero(m_eigv)
l_M = correct_close_to_zero(l_M)
matprint(m_eigv)
print("\n")

print("Eigenvalues (left) of M:")
matprint(l_M)
print("\n")

# Here we check the position with numerical unprecision of the eigenvalue 1
print("Normalizing dominant eigenvector:")
idx_dom = np.where(abs(l_M - 1) < 0.005)[0][0]
dom_eigv_M = m_eigv[:, 0] / sum(m_eigv[:, 0])
matprint(dom_eigv_M)
print("\n")

print("Convergence result of M:")
matprint(np.linalg.matrix_power(M11, 500))
print("\n")

print("equals 1n*w^T")
matprint(np.ones((n_M11,1))@dom_eigv_M[:, None].T)

Random matrix M:
|  0.0996755  0.256674   0.433941  0.109456  0.100254  |
|   0.243224  0.258228  0.0224174  0.229752  0.246379  |
|  0.0481518   0.16604   0.206573  0.261977  0.317258  |
|   0.245418  0.249716   0.108696  0.206788  0.189382  |
|   0.241137   0.22566   0.167584  0.199628  0.165991  |


Left eigenvectors of M:
|  -0.406023+0j  -0.197261+0.474913j  -0.197261-0.474913j  -0.283914+0j   0.0782096+0j  |
|  -0.518969+0j   0.129516+0.172062j   0.129516-0.172062j   -0.73846+0j    0.455553+0j  |
|  -0.394544+0j          0.569211+0j          0.569211+0j   0.287624+0j  -0.0722244+0j  |
|   -0.45107+0j  -0.256574-0.200861j  -0.256574+0.200861j   0.470845+0j   -0.811557+0j  |
|  -0.454629+0j  -0.244892-0.446114j  -0.244892+0.446114j   0.263906+0j    0.350019+0j  |


Eigenvalues (left) of M:
|                 1+0j  |
|  -0.0598045+0.19913j  |
|  -0.0598045-0.19913j  |
|         0.0523745+0j  |
|        0.00448867+0j  |


Normalizing dominant eigenvector:
|  0.182463-0j  |
|   0.23322

## Exercises 2.18

This is similar to exercise 1.4, however, here we actually visualize the graph and its node values. Additionally, we show that the values converge to the initial values multiplied b the dominant left eigenvector as presented in Theorem 2.13 for row stochastic matrices.

First, we define the graphs and their adjacency Matrix A and simulate the results.

In [8]:
# Define x_0
xinitial = np.array([1., -1., 1., -1., 1.])

# Defining the 3 different systems.
# Complete graph
A_complete = np.ones((5,5)) / 5

# Cycle graph
A_cycle = np.array([
    [1/3, 1/3, 0, 0, 1/3],
    [1/3, 1/3, 1/3, 0, 0],
    [0, 1/3, 1/3, 1/3, 0],
    [0, 0, 1/3, 1/3, 1/3],
    [1/3, 0, 0, 1/3,  1/3] ]  )


# Star topology. center = node 1
A_star = np.array([
    [1/5, 1/5, 1/5, 1/5, 1/5],
    [1/2, 1/2, 0, 0, 0], 
    [1/2, 0, 1/2, 0, 0],
    [1/2, 0, 0, 1/2, 0],
    [1/2, 0, 0, 0, 1/2]   ])

# Defining simulation time
ts = 15

# Defining graphs for plotting later
n = 5
G_star = nx.star_graph(n-1)
pos_star = {0:[0.5,0.8], 1:[0.2,0.6],2:[.4,.2],3:[.6,.2],4:[.8,.6]}
G_cycle = nx.cycle_graph(n)
pos_cycle = {0:[0.5,0.8], 1:[0.35,0.6],2:[.4,.3],3:[.6,.3],4:[.65,.6]}
G_complete = nx.complete_graph(n)
pos_complete = pos_cycle.copy()

# Simulating and saving each network
states_complete = lib.simulate_network(A_complete,xinitial, ts)
states_star = lib.simulate_network(A_star,xinitial, ts)
states_cycle = lib.simulate_network(A_cycle,xinitial, ts)

**Complete graph**

Showing complete graph interactive simulation and Theorem 2.13

In [23]:
fig, ax2181 = plt.subplots(figsize=custom_figsize)

# Putting some simulations parts into custom functions
def interactive_network_plot(G, states, pos, t, fig, ax):
    fig, v_bound, pos = lib.init_network_sim_plot(G, states, fig, pos=pos)

    def inter(timestep):
        lib.update_network(timestep['new'], G=G, states_m=states, ax=ax, vbound=v_bound, pos=pos)
        return None

    # Plot initial configuration
    lib.update_network(0, G=G, states_m=states, ax=ax, vbound=v_bound, pos=pos)

    widget = lib.create_widgets_play_slider(fnc=inter, minv=0, maxv=t-1, step=1, play_speed=1000)

    return widget

# If this cell is executed twice we are making sure in the following, that the previous widget instances are all closed
try:
    [c.close() for c in widget2181.children]  # Note: close_all() does also affect plot, thus list compr.
except NameError:  # Only want to except not defined variable error
    pass

widget2181 = interactive_network_plot(G_complete, states_complete, pos_complete, ts, fig, ax2181)

display(widget2181)

# Verifying the results
eigval, eigvec = np.linalg.eig(A_complete.transpose())
idx_dom = np.argmax(eigval)
dom_eigvec = eigvec[0:5,idx_dom]/eigvec[0:5,idx_dom].sum()
print("Showing Theorem 2.13 for the complete graph")
print("Dominant eigenvector: \n", dom_eigvec)
print("Final values : \n", xinitial@dom_eigvec*np.ones(5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Showing Theorem 2.13 for the complete graph
Dominant eigenvector: 
 [0.2 0.2 0.2 0.2 0.2]
Final values : 
 [0.2 0.2 0.2 0.2 0.2]


**Star graph**

Showing star graph interactive simulation and Theorem 2.13

In [24]:
fig, ax2182 = plt.subplots(figsize=custom_figsize)

# If this cell is executed twice we are making sure in the following, that the previous widget instances are all closed
try:
    [c.close() for c in widget2182.children]  # Note: close_all() does also affect plot, thus list compr.
except NameError:  # Only want to except not defined variable error
    pass

widget2182 = interactive_network_plot(G_star, states_star, pos_star, ts, fig, ax2182)

display(widget2182)

# Verifying the results
eigval, eigvec = np.linalg.eig(A_star.transpose() )
idx_dom = np.argmax(eigval)
dom_eigvec = eigvec[0:5,idx_dom]/eigvec[0:5,idx_dom].sum()
print("Showing Theorem 2.13 for the star graph")
print("Dominant eigenvector: \n", dom_eigvec)
print("Final values : \n", xinitial@dom_eigvec*np.ones(5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Showing Theorem 2.13 for the star graph
Dominant eigenvector: 
 [0.38461538 0.15384615 0.15384615 0.15384615 0.15384615]
Final values : 
 [0.38461538 0.38461538 0.38461538 0.38461538 0.38461538]


**Cycle graph**

Showing cycle graph interactive simulation and Theorem 2.13

In [27]:
fig, ax2183 = plt.subplots(figsize=custom_figsize)

# If this cell is executed twice we are making sure in the following, that the previous widget instances are all closed
try:
    [c.close() for c in widget2183.children]  # Note: close_all() does also affect plot, thus list compr.
except NameError:  # Only want to except not defined variable error
    pass

widget2183 = interactive_network_plot(G_cycle, states_cycle, pos_cycle, ts, fig, ax2183)

display(widget2183)

# Verifying the results
eigval, eigvec = np.linalg.eig(A_cycle.transpose())
idx_dom = np.argmax(eigval)
dom_eigvec = eigvec[0:5,idx_dom]/eigvec[0:5,idx_dom].sum()
print("Showing Theorem 2.13 for the cycle graph")
print("Dominant eigenvector: \n", dom_eigvec)
print("Final values : \n", xinitial@dom_eigvec*np.ones(5))

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Showing Theorem 2.13 for the cycle graph
Dominant eigenvector: 
 [0.2 0.2 0.2 0.2 0.2]
Final values : 
 [0.2 0.2 0.2 0.2 0.2]
